// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutritionApi.Data;

#nullable disable

namespace NutritionApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("NutritionApi.Models.Product", b =>
                {
                    b.Property<string>("Barcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Calories")
                        .HasColumnType("REAL");

                    b.Property<double?>("Carbohydrates")
                        .HasColumnType("REAL");

                    b.Property<double?>("Fats")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Proteins")
                        .HasColumnType("REAL");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Barcode");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
